// <auto-generated />
using HotSauceReact.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotSauceReact.Migrations
{
    [DbContext(typeof(HotSauceDbContext))]
    partial class HotSauceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotSauceReact.Models.Cart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserID");

                    b.HasKey("ID");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("HotSauceReact.Models.CartProduct", b =>
                {
                    b.Property<int>("CartID");

                    b.Property<int>("ProductTypeID");

                    b.Property<int>("Quantity");

                    b.Property<int>("TotalCost");

                    b.HasKey("CartID", "ProductTypeID");

                    b.ToTable("CartProducts");
                });

            modelBuilder.Entity("HotSauceReact.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("ProductType");

                    b.HasKey("ID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("HotSauceReact.Models.Sauce", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InventoryQuantity");

                    b.Property<string>("Price");

                    b.Property<int>("ProductID");

                    b.Property<string>("SKU");

                    b.Property<string>("Size");

                    b.Property<int>("SpicyLevel");

                    b.HasKey("ID");

                    b.ToTable("Sauces");
                });

            modelBuilder.Entity("HotSauceReact.Models.Shirt", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Color");

                    b.Property<int>("InventoryQuantity");

                    b.Property<string>("Price");

                    b.Property<int>("ProductID");

                    b.Property<string>("SKU");

                    b.Property<string>("Size");

                    b.HasKey("ID");

                    b.ToTable("Shirts");
                });
#pragma warning restore 612, 618
        }
    }
}
